# API配置
api:
  # OpenAI API密钥
  key: "sk-HgownpFGGCsGNqYs701354E28eE742BfA26eBaDe50874415"
  # API基础URL
  base_url: "http://8.140.63.6:3000/v1"
  # 使用的模型
  model: "claude-3-7-sonnet-latest"
  # 高德地图API密钥
  gaode_key: "5dc52aa6190b78509d95283a0b49d3c3"

# 地理空间分析配置
spatial:
  # 默认坐标系
  default_crs: "EPSG:4326"
  # 距离单位
  distance_unit: "km"

# 调试选项
debug:
  enabled: false
  log_level: "info" 